from __future__ import annotations

from typing import Any


# Curated demo catalog override data.
# Product names intentionally follow the selected image source.
PRODUCT_OVERRIDES: dict[str, dict[str, Any]] = {'anime-acrylic-stand': {'category': '运动户外',
                         'description': '美式橄榄球摆件主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['american football'],
                         'name': '美式橄榄球摆件',
                         'original_price': 109.0,
                         'price': 89.0,
                         'seller_name': 'xiaohong'},
 'anime-badge-book': {'category': '运动户外',
                      'description': '绿色街车摩托主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['kawasaki z800'],
                      'name': '绿色街车摩托',
                      'original_price': 82.0,
                      'price': 66.0,
                      'seller_name': 'xiaohong'},
 'anime-card-sleeves': {'category': '运动户外',
                        'description': '经典足球摆件主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['football'],
                        'name': '经典足球摆件',
                        'original_price': 38.0,
                        'price': 28.0,
                        'seller_name': 'xiaohong'},
 'anime-cup-sleeve': {'category': '运动户外',
                      'description': '城市通勤摩托车主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['generic motorcycle'],
                      'name': '城市通勤摩托车',
                      'original_price': 52.0,
                      'price': 39.0,
                      'seller_name': 'xiaohong'},
 'anime-desk-calendar': {'category': '运动户外',
                         'description': '高尔夫球组合主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['golf ball'],
                         'name': '高尔夫球组合',
                         'original_price': 88.0,
                         'price': 68.0,
                         'seller_name': 'xiaohong'},
 'anime-desk-figure': {'category': '运动户外',
                       'description': '篮球框装饰件主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['basketball rim'],
                       'name': '篮球框装饰件',
                       'original_price': 149.0,
                       'price': 128.0,
                       'seller_name': 'xiaohong'},
 'anime-display-rack': {'category': '运动户外',
                        'description': '白色踏板摩托车主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['scooter motorcycle'],
                        'name': '白色踏板摩托车',
                        'original_price': 139.0,
                        'price': 119.0,
                        'seller_name': 'xiaohong'},
 'anime-ita-pouch': {'category': '运动户外',
                     'description': '红色板球收藏球主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['cricket ball'],
                     'name': '红色板球收藏球',
                     'original_price': 169.0,
                     'price': 139.0,
                     'seller_name': 'xiaohong'},
 'anime-keychain-gift': {'category': '运动户外',
                         'description': '白色棒球摆件主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['baseball ball'],
                         'name': '白色棒球摆件',
                         'original_price': 76.0,
                         'price': 58.0,
                         'seller_name': 'xiaohong'},
 'anime-lanyard-card': {'category': '运动户外',
                        'description': '板球门柱套件主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['cricket wicket'],
                        'name': '板球门柱套件',
                        'original_price': 45.0,
                        'price': 35.0,
                        'seller_name': 'xiaohong'},
 'anime-mini-lightbox': {'category': '运动户外',
                         'description': '荧光网球组合主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['tennis ball'],
                         'name': '荧光网球组合',
                         'original_price': 142.0,
                         'price': 118.0,
                         'seller_name': 'xiaohong'},
 'anime-mousepad': {'category': '运动户外',
                    'description': '深色板球头盔主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                    'download_queries': ['cricket helmet'],
                    'name': '深色板球头盔',
                    'original_price': 96.0,
                    'price': 79.0,
                    'seller_name': 'xiaohong'},
 'anime-photo-card-book': {'category': '运动户外',
                           'description': '金属棒球棒主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                           'download_queries': ['metal baseball bat'],
                           'name': '金属棒球棒',
                           'original_price': 89.0,
                           'price': 72.0,
                           'seller_name': 'xiaohong'},
 'anime-pin-banner': {'category': '运动户外',
                      'description': '红白网球拍主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['tennis racket'],
                      'name': '红白网球拍',
                      'original_price': 74.0,
                      'price': 58.0,
                      'seller_name': 'xiaohong'},
 'anime-plush-keyring': {'category': '运动户外',
                         'description': '橙色篮球摆件主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['basketball'],
                         'name': '橙色篮球摆件',
                         'original_price': 88.0,
                         'price': 72.0,
                         'seller_name': 'xiaohong'},
 'anime-postcard-set': {'category': '运动户外',
                        'description': '木质板球球棒主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['cricket bat'],
                        'name': '木质板球球棒',
                        'original_price': 58.0,
                        'price': 45.0,
                        'seller_name': 'xiaohong'},
 'anime-shaker-charm': {'category': '运动户外',
                        'description': '金属高尔夫球杆主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['iron golf'],
                        'name': '金属高尔夫球杆',
                        'original_price': 82.0,
                        'price': 64.0,
                        'seller_name': 'xiaohong'},
 'anime-stamp-set': {'category': '运动户外',
                     'description': '蓝黄排球摆件主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['volleyball'],
                     'name': '蓝黄排球摆件',
                     'original_price': 59.0,
                     'price': 46.0,
                     'seller_name': 'xiaohong'},
 'anime-sticker-pack': {'category': '运动户外',
                        'description': '复古棒球手套主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['baseball glove'],
                        'name': '复古棒球手套',
                        'original_price': 49.0,
                        'price': 39.0,
                        'seller_name': 'xiaohong'},
 'anime-towel': {'category': '运动户外',
                 'description': '白色羽毛球主体清楚、背景干净，适合在运动户外页面中直接展示，商品名称与主图保持一致。',
                 'download_queries': ['feather shuttlecock'],
                 'name': '白色羽毛球',
                 'original_price': 68.0,
                 'price': 52.0,
                 'seller_name': 'xiaohong'},
 'beauty-blush-cloud': {'category': '美妆个护',
                        'description': '阳光柑橘淡香水主体清楚、背景干净，适合在美妆个护页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['dolce shine eau'],
                        'name': '阳光柑橘淡香水',
                        'original_price': 98.0,
                        'price': 79.0,
                        'seller_name': 'xiaomei'},
 'beauty-body-mist': {'category': '美妆个护',
                      'description': '花香调随身香水主体清楚、背景干净，适合在美妆个护页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['dior adore'],
                      'name': '花香调随身香水',
                      'original_price': 148.0,
                      'price': 118.0,
                      'seller_name': 'xiaomei'},
 'beauty-cleanser': {'category': '美妆个护',
                     'description': '柔雾定妆散粉罐主体清楚、背景干净，适合在美妆个护页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['powder canister'],
                     'name': '柔雾定妆散粉罐',
                     'original_price': 106.0,
                     'price': 88.0,
                     'seller_name': 'xiaomei'},
 'beauty-essence-classic': {'category': '美妆个护',
                            'description': '纤长卷翘睫毛膏主体清楚、背景干净，适合在美妆个护页面中直接展示，商品名称与主图保持一致。',
                            'download_queries': ['essence mascara lash'],
                            'name': '纤长卷翘睫毛膏',
                            'original_price': 319.0,
                            'price': 259.0,
                            'seller_name': 'xiaomei'},
 'beauty-face-mask': {'category': '美妆个护',
                      'description': '男士身体乳主体清楚、背景干净，适合在美妆个护页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['vaseline men body'],
                      'name': '男士身体乳',
                      'original_price': 112.0,
                      'price': 88.0,
                      'seller_name': 'xiaomei'},
 'beauty-foundation': {'category': '美妆个护',
                       'description': '正红丝绒口红主体清楚、背景干净，适合在美妆个护页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['lipstick'],
                       'name': '正红丝绒口红',
                       'original_price': 209.0,
                       'price': 169.0,
                       'seller_name': 'xiaomei'},
 'beauty-hair-oil': {'category': '美妆个护',
                     'description': '滋润沐浴乳主体清楚、背景干净，适合在美妆个护页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['olay ultra moisture'],
                     'name': '滋润沐浴乳',
                     'original_price': 149.0,
                     'price': 118.0,
                     'seller_name': 'xiaomei'},
 'beauty-hand-cream': {'category': '美妆个护',
                       'description': '黑可可木质香水主体清楚、背景干净，适合在美妆个护页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['chanel coco noir'],
                       'name': '黑可可木质香水',
                       'original_price': 79.0,
                       'price': 62.0,
                       'seller_name': 'xiaomei'},
 'beauty-lip-gloss': {'category': '美妆个护',
                      'description': '繁花香调淡香水主体清楚、背景干净，适合在美妆个护页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['gucci bloom eau'],
                      'name': '繁花香调淡香水',
                      'original_price': 126.0,
                      'price': 98.0,
                      'seller_name': 'xiaomei'},
 'beauty-lipstick': {'category': '美妆个护',
                     'description': '清爽中性淡香水主体清楚、背景干净，适合在美妆个护页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['calvin klein ck'],
                     'name': '清爽中性淡香水',
                     'original_price': 159.0,
                     'price': 129.0,
                     'seller_name': 'xiaomei'},
 'beauty-lotion-soft': {'category': '美妆个护',
                        'description': '眼影盘主体完整，颜色清楚，适合作为美妆个护类测试商品和价格提醒商品。',
                        'download_queries': ['makeup flatlay'],
                        'name': '镜面多色眼影盘套装',
                        'original_price': 249.0,
                        'price': 199.0,
                        'seller_name': 'xiaomei'},
 'beauty-makeup-brush': {'category': '美妆个护',
                         'description': '温和绿叶洗手液主体清楚、背景干净，适合在美妆个护页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['attitude super leaves'],
                         'name': '温和绿叶洗手液',
                         'original_price': 186.0,
                         'price': 149.0,
                         'seller_name': 'xiaomei'},
 'beauty-perfume-mini': {'category': '潮流穿搭',
                         'description': '绿色水晶耳环主体清楚，适合放在潮流穿搭分类中展示首饰搭配。',
                         'download_queries': ['crystal earring'],
                         'name': '绿色水晶耳环',
                         'original_price': 168.0,
                         'price': 136.0,
                         'seller_name': 'xiaomei'},
 'beauty-sunscreen': {'category': '美妆个护',
                      'description': '樱桃红亮面指甲油主体清楚、背景干净，适合在美妆个护页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['nail polish'],
                      'name': '樱桃红亮面指甲油',
                      'original_price': 118.0,
                      'price': 96.0,
                      'seller_name': 'xiaomei'},
 'culture-cd-wallet': {'category': '餐厨好物',
                       'description': '红白手持料理棒主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['hand blender'],
                       'name': '红白手持料理棒',
                       'original_price': 116.0,
                       'price': 92.0,
                       'seller_name': 'sunqi'},
 'culture-desk-easel': {'category': '餐厨好物',
                        'description': '黑色四面刨丝器主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['grater'],
                        'name': '黑色四面刨丝器',
                        'original_price': 86.0,
                        'price': 68.0,
                        'seller_name': 'sunqi'},
 'culture-illustration-book': {'category': '餐厨好物',
                               'description': '黄色柠檬榨汁器主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                               'download_queries': ['citrus squeezer yellow'],
                               'name': '黄色柠檬榨汁器',
                               'original_price': 116.0,
                               'price': 92.0,
                               'seller_name': 'sunqi'},
 'culture-notebook-grid': {'category': '餐厨好物',
                           'description': '黑色手持打蛋器主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                           'download_queries': ['whisk'],
                           'name': '黑色手持打蛋器',
                           'original_price': 56.0,
                           'price': 42.0,
                           'seller_name': 'sunqi'},
 'culture-pen-case': {'category': '餐厨好物',
                      'description': '盒装料理机主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['boxed blender'],
                      'name': '盒装料理机',
                      'original_price': 72.0,
                      'price': 59.0,
                      'seller_name': 'sunqi'},
 'culture-pen-set': {'category': '餐厨好物',
                     'description': '蓝色冰格托盘主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['ice cube tray'],
                     'name': '蓝色冰格托盘',
                     'original_price': 64.0,
                     'price': 49.0,
                     'seller_name': 'sunqi'},
 'culture-photo-frame': {'category': '餐厨好物',
                         'description': '细网过滤筛主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['fine mesh strainer'],
                         'name': '细网过滤筛',
                         'original_price': 92.0,
                         'price': 73.0,
                         'seller_name': 'sunqi'},
 'culture-poster-set': {'category': '餐厨好物',
                        'description': '黄色鸡蛋切片器主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['egg slicer'],
                        'name': '黄色鸡蛋切片器',
                        'original_price': 136.0,
                        'price': 109.0,
                        'seller_name': 'sunqi'},
 'culture-print-poster': {'category': '餐厨好物',
                          'description': '木质切菜板主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                          'download_queries': ['chopping board'],
                          'name': '木质切菜板',
                          'original_price': 109.0,
                          'price': 88.0,
                          'seller_name': 'sunqi'},
 'culture-reading-kit': {'category': '餐厨好物',
                         'description': '碳钢家用炒锅主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['carbon steel wok'],
                         'name': '碳钢家用炒锅',
                         'original_price': 96.0,
                         'price': 76.0,
                         'seller_name': 'sunqi'},
 'culture-reading-lamp': {'category': '餐厨好物',
                          'description': '木柄厨房过滤勺主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                          'download_queries': ['kitchen sieve'],
                          'name': '木柄厨房过滤勺',
                          'original_price': 108.0,
                          'price': 86.0,
                          'seller_name': 'sunqi'},
 'culture-stationery-red': {'category': '餐厨好物',
                            'description': '竹制厨房刮刀主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                            'download_queries': ['bamboo spatula'],
                            'name': '竹制厨房刮刀',
                            'original_price': 86.0,
                            'price': 68.0,
                            'seller_name': 'sunqi'},
 'culture-sticker-sheet': {'category': '餐厨好物',
                           'description': '不锈钢餐叉主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                           'download_queries': ['fork'],
                           'name': '不锈钢餐叉',
                           'original_price': 42.0,
                           'price': 32.0,
                           'seller_name': 'sunqi'},
 'culture-vinyl-decor': {'category': '餐厨好物',
                         'description': '锋利厨房刀具主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['knife'],
                         'name': '锋利厨房刀具',
                         'original_price': 168.0,
                         'price': 138.0,
                         'seller_name': 'sunqi'},
 'culture-washi-tape': {'category': '餐厨好物',
                        'description': '黑色嵌入式电陶炉主体清楚、背景干净，适合在餐厨好物页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['electric stove'],
                        'name': '黑色嵌入式电陶炉',
                        'original_price': 46.0,
                        'price': 36.0,
                        'seller_name': 'sunqi'},
 'desk-cable-dock': {'category': '桌搭数码',
                     'description': '智能语音桌面音箱主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['amazon echo plus'],
                     'name': '智能语音桌面音箱',
                     'original_price': 89.0,
                     'price': 69.0,
                     'seller_name': 'lisi'},
 'desk-camera-canon-eos': {'category': '桌搭数码',
                           'description': '佳能 EOS 机身轮廓清楚，适合展示相机类商品详情，也是第 6 章搜索测试保留商品。',
                           'download_queries': ['canon eos camera'],
                           'name': '佳能 EOS R50 微单相机',
                           'original_price': 5199.0,
                           'price': 4699.0,
                           'seller_name': 'lisi'},
 'desk-camera-pouch': {'category': '桌搭数码',
                       'description': 'Dell XPS 13 轻薄本主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['dell xps 13'],
                       'name': 'Dell XPS 13 轻薄本',
                       'original_price': 176.0,
                       'price': 148.0,
                       'seller_name': 'lisi'},
 'desk-earbud-case': {'category': '桌搭数码',
                      'description': '磁吸移动电源主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['apple magsafe battery'],
                      'name': '磁吸移动电源',
                      'original_price': 68.0,
                      'price': 49.0,
                      'seller_name': 'lisi'},
 'desk-headphones-shell': {'category': '桌搭数码',
                           'description': 'Oppo A57 智能手机主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                           'download_queries': ['oppo a57'],
                           'name': 'Oppo A57 智能手机',
                           'original_price': 359.0,
                           'price': 299.0,
                           'seller_name': 'lisi'},
 'desk-headphones-sony-wh1000xm5': {'category': '桌搭数码',
                                    'description': '银白头戴耳机主体干净，适合通勤和学习场景，降噪耳机搜索测试会命中该商品。',
                                    'download_queries': ['sony headphones'],
                                    'name': '索尼 WH-1000XM5 降噪耳机',
                                    'original_price': 2799.0,
                                    'price': 2399.0,
                                    'seller_name': 'lisi'},
 'desk-keyboard-75': {'category': '桌搭数码',
                      'description': '浅色键帽和紧凑 75 键布局更适合宿舍与办公桌面，机械键盘搜索测试会命中该商品。',
                      'download_queries': ['mechanical keyboard'],
                      'name': '海盐轴 75 键机械键盘',
                      'original_price': 499.0,
                      'price': 429.0,
                      'seller_name': 'lisi'},
 'desk-keycaps-soda': {'category': '桌搭数码',
                       'description': '双屏笔记本适合展示桌搭数码类商品，保留原测试 slug 以支持商家发货流程。',
                       'download_queries': ['desktop workstation'],
                       'name': '双屏创作笔记本工作站',
                       'original_price': 1099.0,
                       'price': 899.0,
                       'seller_name': 'lisi'},
 'desk-laptop-stand': {'category': '桌搭数码',
                       'description': '经典 iPhone 6 手机主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['iphone'],
                       'name': '经典 iPhone 6 手机',
                       'original_price': 198.0,
                       'price': 159.0,
                       'seller_name': 'lisi'},
 'desk-light-strip': {'category': '桌搭数码',
                      'description': '白色无线蓝牙耳机主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['apple airpods'],
                      'name': '白色无线蓝牙耳机',
                      'original_price': 118.0,
                      'price': 95.0,
                      'seller_name': 'lisi'},
 'desk-monitor-riser': {'category': '桌搭数码',
                        'description': '深灰智能桌面音箱主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['apple homepod mini'],
                        'name': '深灰智能桌面音箱',
                        'original_price': 169.0,
                        'price': 139.0,
                        'seller_name': 'lisi'},
 'desk-mouse-glasspad': {'category': '桌搭数码',
                         'description': '经典 iPhone 5s 手机主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['iphone 5s'],
                         'name': '经典 iPhone 5s 手机',
                         'original_price': 208.0,
                         'price': 169.0,
                         'seller_name': 'lisi'},
 'desk-phone-stand': {'category': '桌搭数码',
                      'description': '银色头戴式蓝牙耳机主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['apple airpods max'],
                      'name': '银色头戴式蓝牙耳机',
                      'original_price': 99.0,
                      'price': 79.0,
                      'seller_name': 'lisi'},
 'desk-speaker-mini': {'category': '桌搭数码',
                       'description': 'MacBook Pro 深空灰笔记本主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['apple macbook pro'],
                       'name': 'MacBook Pro 深空灰笔记本',
                       'original_price': 239.0,
                       'price': 189.0,
                       'seller_name': 'lisi'},
 'desk-tablet-sleeve': {'category': '桌搭数码',
                        'description': '联想 Yoga 翻转笔记本主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['lenovo yoga 920'],
                        'name': '联想 Yoga 翻转笔记本',
                        'original_price': 109.0,
                        'price': 89.0,
                        'seller_name': 'lisi'},
 'desk-usb-hub': {'category': '桌搭数码',
                  'description': 'iPhone 13 Pro 手机主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                  'download_queries': ['iphone 13 pro'],
                  'name': 'iPhone 13 Pro 手机',
                  'original_price': 229.0,
                  'price': 189.0,
                  'seller_name': 'lisi'},
 'desk-watch-softlight': {'category': '桌搭数码',
                          'description': '华为 MateBook 轻薄本主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                          'download_queries': ['huawei matebook pro'],
                          'name': '华为 MateBook 轻薄本',
                          'original_price': 159.0,
                          'price': 129.0,
                          'seller_name': 'lisi'},
 'desk-webcam-light': {'category': '桌搭数码',
                       'description': '梅子色磁吸手机壳主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['iphone 12 silicone'],
                       'name': '梅子色磁吸手机壳',
                       'original_price': 179.0,
                       'price': 148.0,
                       'seller_name': 'lisi'},
 'desk-wireless-charger': {'category': '桌搭数码',
                           'description': '颈挂式无线耳机主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                           'download_queries': ['beats flex wireless'],
                           'name': '颈挂式无线耳机',
                           'original_price': 159.0,
                           'price': 129.0,
                           'seller_name': 'lisi'},
 'desk-wireless-mic': {'category': '桌搭数码',
                       'description': '黑色 iPhone X 手机主体清楚、背景干净，适合在桌搭数码页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['iphone'],
                       'name': '黑色 iPhone X 手机',
                       'original_price': 268.0,
                       'price': 219.0,
                       'seller_name': 'lisi'},
 'home-bedding-check': {'category': '家居日用',
                        'description': '木质马克杯架主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['mug tree stand'],
                        'name': '木质马克杯架',
                        'original_price': 399.0,
                        'price': 329.0,
                        'seller_name': 'zhouba'},
 'home-bedside-tray': {'category': '家居日用',
                       'description': '木质擀面杖主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['wooden rolling pin'],
                       'name': '木质擀面杖',
                       'original_price': 108.0,
                       'price': 86.0,
                       'seller_name': 'zhouba'},
 'home-book-stand': {'category': '家居日用',
                     'description': '木质香料收纳架主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['spice rack'],
                     'name': '木质香料收纳架',
                     'original_price': 148.0,
                     'price': 119.0,
                     'seller_name': 'zhouba'},
 'home-candle-amber': {'category': '家居日用',
                       'description': '木质浴室镜柜套装主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['wooden bathroom sink'],
                       'name': '木质浴室镜柜套装',
                       'original_price': 108.0,
                       'price': 86.0,
                       'seller_name': 'zhouba'},
 'home-curtain-soft': {'category': '家居日用',
                       'description': '樱桃木床头柜主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['bedside table african'],
                       'name': '樱桃木床头柜',
                       'original_price': 329.0,
                       'price': 269.0,
                       'seller_name': 'zhouba'},
 'home-diffuser-clear': {'category': '家居日用',
                         'description': '藤编装饰秋千椅主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['decoration swing'],
                         'name': '藤编装饰秋千椅',
                         'original_price': 158.0,
                         'price': 128.0,
                         'seller_name': 'zhouba'},
 'home-floor-lamp': {'category': '家居日用',
                     'description': '保留当前观感较好的客厅落地灯主图，作为全目录商品卡片质量基准。',
                     'download_queries': ['livingroom lamp'],
                     'name': '北欧客厅落地灯套装',
                     'original_price': 399.0,
                     'price': 339.0,
                     'seller_name': 'zhouba'},
 'home-glass-vase': {'category': '家居日用',
                     'description': '浅灰现代客厅沙发主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['annibale colombo sofa'],
                     'name': '浅灰现代客厅沙发',
                     'original_price': 149.0,
                     'price': 118.0,
                     'seller_name': 'zhouba'},
 'home-incense-holder': {'category': '家居日用',
                         'description': '玻璃盖银色汤锅主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['pot glass cap'],
                         'name': '玻璃盖银色汤锅',
                         'original_price': 96.0,
                         'price': 78.0,
                         'seller_name': 'zhouba'},
 'home-linen-basket': {'category': '家居日用',
                       'description': '浅木餐盘托盘主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['tray'],
                       'name': '浅木餐盘托盘',
                       'original_price': 136.0,
                       'price': 109.0,
                       'seller_name': 'zhouba'},
 'home-lounge-corner': {'category': '家居日用',
                        'description': '米白弧背办公椅主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['knoll saarinen executive'],
                        'name': '米白弧背办公椅',
                        'original_price': 539.0,
                        'price': 459.0,
                        'seller_name': 'zhouba'},
 'home-mug-ceramic': {'category': '家居日用',
                      'description': '家庭树相框摆件主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['family tree photo'],
                      'name': '家庭树相框摆件',
                      'original_price': 76.0,
                      'price': 59.0,
                      'seller_name': 'zhouba'},
 'home-room-spray': {'category': '家居日用',
                     'description': '陶土绿植花盆主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['plant pot'],
                     'name': '陶土绿植花盆',
                     'original_price': 128.0,
                     'price': 98.0,
                     'seller_name': 'zhouba'},
 'home-side-table': {'category': '家居日用',
                     'description': '黄色削皮器主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['yellow peeler'],
                     'name': '黄色削皮器',
                     'original_price': 219.0,
                     'price': 179.0,
                     'seller_name': 'zhouba'},
 'home-storage-crate': {'category': '家居日用',
                        'description': '暖光桌面台灯主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['table lamp'],
                        'name': '暖光桌面台灯',
                        'original_price': 99.0,
                        'price': 82.0,
                        'seller_name': 'zhouba'},
 'home-table-mirror': {'category': '家居日用',
                       'description': '白色陶瓷餐盘主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['plate'],
                       'name': '白色陶瓷餐盘',
                       'original_price': 169.0,
                       'price': 138.0,
                       'seller_name': 'zhouba'},
 'home-throw-pillows': {'category': '家居日用',
                        'description': '米色软包双人床主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['annibale colombo bed'],
                        'name': '米色软包双人床',
                        'original_price': 169.0,
                        'price': 139.0,
                        'seller_name': 'zhouba'},
 'home-tray-softlight': {'category': '家居日用',
                         'description': '绿植小屋桌面摆件主体清楚、背景干净，适合在家居日用页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['house showpiece plant'],
                         'name': '绿植小屋桌面摆件',
                         'original_price': 88.0,
                         'price': 69.0,
                         'seller_name': 'zhouba'},
 'snack-candy-box': {'category': '食品饮品',
                     'description': '果汁饮品瓶主体清楚、背景干净，适合在食品饮品页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['juice'],
                     'name': '果汁饮品瓶',
                     'original_price': 72.0,
                     'price': 58.0,
                     'seller_name': 'xiaogang'},
 'snack-choco-wafer': {'category': '食品饮品',
                       'description': '蛋白粉补给罐主体清楚、背景干净，适合在食品饮品页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['protein powder'],
                       'name': '蛋白粉补给罐',
                       'original_price': 34.0,
                       'price': 24.0,
                       'seller_name': 'xiaogang'},
 'snack-cookies': {'category': '食品饮品',
                   'description': '清爽黄瓜组合主体清楚、背景干净，适合在食品饮品页面中直接展示，商品名称与主图保持一致。',
                   'download_queries': ['cucumber'],
                   'name': '清爽黄瓜组合',
                   'original_price': 36.0,
                   'price': 26.0,
                   'seller_name': 'xiaogang'},
 'snack-drip-coffee': {'category': '食品饮品',
                       'description': '家用烹饪油瓶主体清楚、背景干净，适合在食品饮品页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['cooking oil'],
                       'name': '家用烹饪油瓶',
                       'original_price': 62.0,
                       'price': 49.0,
                       'seller_name': 'xiaogang'},
 'snack-fruit-tea-jar': {'category': '食品饮品',
                         'description': '桑葚鲜果盒主体清楚、背景干净，适合在食品饮品页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['mulberry'],
                         'name': '桑葚鲜果盒',
                         'original_price': 78.0,
                         'price': 62.0,
                         'seller_name': 'xiaogang'},
 'snack-jelly-pack': {'category': '食品饮品',
                      'description': '柠檬气泡软饮主体清楚、背景干净，适合在食品饮品页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['soft drinks'],
                      'name': '柠檬气泡软饮',
                      'original_price': 46.0,
                      'price': 36.0,
                      'seller_name': 'xiaogang'},
 'snack-matcha-latte': {'category': '食品饮品',
                        'description': '纯牛奶瓶装组合主体清楚、背景干净，适合在食品饮品页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['milk'],
                        'name': '纯牛奶瓶装组合',
                        'original_price': 58.0,
                        'price': 46.0,
                        'seller_name': 'xiaogang'},
 'snack-nut-gift': {'category': '食品饮品',
                    'description': '红富士苹果礼盒主体清楚、背景干净，适合在食品饮品页面中直接展示，商品名称与主图保持一致。',
                    'download_queries': ['apple'],
                    'name': '红富士苹果礼盒',
                    'original_price': 108.0,
                    'price': 89.0,
                    'seller_name': 'xiaogang'},
 'snack-oat-bites': {'category': '食品饮品',
                     'description': '香草冰淇淋杯主体清楚、背景干净，适合在食品饮品页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['ice'],
                     'name': '香草冰淇淋杯',
                     'original_price': 42.0,
                     'price': 32.0,
                     'seller_name': 'xiaogang'},
 'snack-party-pack': {'category': '食品饮品',
                      'description': '奇异果鲜果盒主体清楚、背景干净，适合在食品饮品页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['kiwi'],
                      'name': '奇异果鲜果盒',
                      'original_price': 86.0,
                      'price': 68.0,
                      'seller_name': 'xiaogang'},
 'snack-popcorn-tin': {'category': '食品饮品',
                       'description': 'Nescafe 咖啡罐主体清楚、背景干净，适合在食品饮品页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['nescafe coffee'],
                       'name': 'Nescafe 咖啡罐',
                       'original_price': 74.0,
                       'price': 58.0,
                       'seller_name': 'xiaogang'},
 'snack-sparkling': {'category': '食品饮品',
                     'description': '草莓鲜果盒主体清楚、背景干净，适合在食品饮品页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['strawberry'],
                     'name': '草莓鲜果盒',
                     'original_price': 46.0,
                     'price': 36.0,
                     'seller_name': 'xiaogang'},
 'snack-tea-pack': {'category': '食品饮品',
                    'description': '玻璃蜂蜜罐主体清楚、背景干净，适合在食品饮品页面中直接展示，商品名称与主图保持一致。',
                    'download_queries': ['honey jar'],
                    'name': '玻璃蜂蜜罐',
                    'original_price': 49.0,
                    'price': 39.0,
                    'seller_name': 'xiaogang'},
 'snack-yogurt-cup': {'category': '食品饮品',
                      'description': '柠檬鲜果组合主体清楚、背景干净，适合在食品饮品页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['lemon'],
                      'name': '柠檬鲜果组合',
                      'original_price': 56.0,
                      'price': 45.0,
                      'seller_name': 'xiaogang'},
 'travel-cable-pouch': {'category': '出行日用',
                        'description': '伸缩自拍杆主体清楚、背景干净，适合在出行日用页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['selfie stick monopod'],
                        'name': '伸缩自拍杆',
                        'original_price': 96.0,
                        'price': 76.0,
                        'seller_name': 'zhouba'},
 'travel-fragrance': {'category': '出行日用',
                      'description': '不锈钢便携餐勺主体清楚、背景干净，适合在出行日用页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['spoon'],
                      'name': '不锈钢便携餐勺',
                      'original_price': 68.0,
                      'price': 55.0,
                      'seller_name': 'zhouba'},
 'travel-inflator': {'category': '出行日用',
                     'description': '迷彩车载纸巾盒主体清楚、背景干净，适合在出行日用页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['tissue paper box'],
                     'name': '迷彩车载纸巾盒',
                     'original_price': 208.0,
                     'price': 169.0,
                     'seller_name': 'zhouba'},
 'travel-jump-starter': {'category': '出行日用',
                         'description': '便携午餐盒主体清楚、背景干净，适合在出行日用页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['lunch box'],
                         'name': '便携午餐盒',
                         'original_price': 159.0,
                         'price': 129.0,
                         'seller_name': 'zhouba'},
 'travel-luggage-tag': {'category': '出行日用',
                        'description': '星光色 iPad mini 平板主体清楚、背景干净，适合在出行日用页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['ipad mini 2021'],
                        'name': '星光色 iPad mini 平板',
                        'original_price': 56.0,
                        'price': 42.0,
                        'seller_name': 'zhouba'},
 'travel-mini-bottle': {'category': '出行日用',
                        'description': '三星 Tab S8 灰色平板主体清楚、背景干净，适合在出行日用页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['samsung galaxy tab'],
                        'name': '三星 Tab S8 灰色平板',
                        'original_price': 52.0,
                        'price': 39.0,
                        'seller_name': 'zhouba'},
 'travel-neck-pillow': {'category': '出行日用',
                        'description': '白色磁吸移动电源主体清楚、背景干净，适合在出行日用页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['selfie lamp iphone'],
                        'name': '白色磁吸移动电源',
                        'original_price': 159.0,
                        'price': 129.0,
                        'seller_name': 'zhouba'},
 'travel-organizer': {'category': '出行日用',
                      'description': '黑色铝制随行杯主体清楚、背景干净，适合在出行日用页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['aluminium cup'],
                      'name': '黑色铝制随行杯',
                      'original_price': 156.0,
                      'price': 129.0,
                      'seller_name': 'zhouba'},
 'travel-packing-cubes': {'category': '出行日用',
                          'description': '透明玻璃杯主体清楚、背景干净，适合在出行日用页面中直接展示，商品名称与主图保持一致。',
                          'download_queries': ['glass'],
                          'name': '透明玻璃杯',
                          'original_price': 88.0,
                          'price': 69.0,
                          'seller_name': 'zhouba'},
 'travel-passport-wallet': {'category': '出行日用',
                            'description': '轻量自拍支架主体清楚、背景干净，适合在出行日用页面中直接展示，商品名称与主图保持一致。',
                            'download_queries': ['monopod'],
                            'name': '轻量自拍支架',
                            'original_price': 122.0,
                            'price': 96.0,
                            'seller_name': 'zhouba'},
 'travel-phone-mount': {'category': '出行日用',
                        'description': '瓶装饮用水主体清楚、背景干净，适合在出行日用页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['water'],
                        'name': '瓶装饮用水',
                        'original_price': 99.0,
                        'price': 79.0,
                        'seller_name': 'zhouba'},
 'travel-vacuum': {'category': '出行日用',
                   'description': '白色三星平板电脑主体清楚、背景干净，适合在出行日用页面中直接展示，商品名称与主图保持一致。',
                   'download_queries': ['samsung galaxy tab'],
                   'name': '白色三星平板电脑',
                   'original_price': 169.0,
                   'price': 139.0,
                   'seller_name': 'zhouba'},
 'wear-baseball-cap': {'category': '潮流穿搭',
                       'description': '黑色简约手提包主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                       'download_queries': ['handbag'],
                       'name': '黑色简约手提包',
                       'original_price': 109.0,
                       'price': 89.0,
                       'seller_name': 'xiaoming'},
 'wear-canvas-crossbody': {'category': '潮流穿搭',
                           'description': '包型清楚、质感干净，适合日常通勤和短途出门，保留原测试 slug 以支持取消订单流程。',
                           'download_queries': ['canvas bag'],
                           'name': '棕色皮革通勤斜挎包',
                           'original_price': 188.0,
                           'price': 149.0,
                           'seller_name': 'xiaoming'},
 'wear-cardigan-knit': {'category': '潮流穿搭',
                        'description': '黑棕居家拖鞋主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['slipper'],
                        'name': '黑棕居家拖鞋',
                        'original_price': 246.0,
                        'price': 199.0,
                        'seller_name': 'xiaoming'},
 'wear-denim-soft': {'category': '潮流穿搭',
                     'description': '黑色链条通勤包主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                     'download_queries': ['prada'],
                     'name': '黑色链条通勤包',
                     'original_price': 299.0,
                     'price': 239.0,
                     'seller_name': 'xiaoming'},
 'wear-hairclip-gift': {'category': '潮流穿搭',
                        'description': '经典深色太阳镜主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['sun glasses'],
                        'name': '经典深色太阳镜',
                        'original_price': 72.0,
                        'price': 56.0,
                        'seller_name': 'xiaoming'},
 'wear-hoodie-soft': {'category': '潮流穿搭',
                      'description': '祖母绿椭圆耳环主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['oval earring'],
                      'name': '祖母绿椭圆耳环',
                      'original_price': 269.0,
                      'price': 219.0,
                      'seller_name': 'xiaoming'},
 'wear-layer-necklace': {'category': '潮流穿搭',
                         'description': '金色女士单鞋主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['golden shoes woman'],
                         'name': '金色女士单鞋',
                         'original_price': 112.0,
                         'price': 89.0,
                         'seller_name': 'xiaoming'},
 'wear-mini-backpack': {'category': '潮流穿搭',
                        'description': '热带花叶耳环主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['tropical earring'],
                        'name': '热带花叶耳环',
                        'original_price': 209.0,
                        'price': 169.0,
                        'seller_name': 'xiaoming'},
 'wear-phone-strap': {'category': '潮流穿搭',
                      'description': '黑色太阳镜主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                      'download_queries': ['sun glasses'],
                      'name': '黑色太阳镜',
                      'original_price': 45.0,
                      'price': 35.0,
                      'seller_name': 'xiaoming'},
 'wear-pleated-skirt': {'category': '潮流穿搭',
                        'description': '黑色高跟鞋主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['calvin klein heel'],
                        'name': '黑色高跟鞋',
                        'original_price': 209.0,
                        'price': 169.0,
                        'seller_name': 'xiaoming'},
 'wear-shoulder-bag-soft': {'category': '潮流穿搭',
                            'description': '粉色休闲鞋主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                            'download_queries': ['pampi shoes'],
                            'name': '粉色休闲鞋',
                            'original_price': 232.0,
                            'price': 189.0,
                            'seller_name': 'xiaoming'},
 'wear-slip-ons': {'category': '潮流穿搭',
                   'description': '银色女士腕表主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                   'download_queries': ['iwc ingenieur automatic'],
                   'name': '银色女士腕表',
                   'original_price': 186.0,
                   'price': 149.0,
                   'seller_name': 'xiaoming'},
 'wear-sneaker-retro': {'category': '潮流穿搭',
                        'description': '月相女士腕表主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                        'download_queries': ['rolex cellini moonphase'],
                        'name': '月相女士腕表',
                        'original_price': 399.0,
                        'price': 329.0,
                        'seller_name': 'xiaoming'},
 'wear-socks-pop': {'category': '潮流穿搭',
                    'description': '轻便旅行太阳镜主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                    'download_queries': ['sunglasses'],
                    'name': '轻便旅行太阳镜',
                    'original_price': 54.0,
                    'price': 42.0,
                    'seller_name': 'xiaoming'},
 'wear-sunglasses-clear': {'category': '潮流穿搭',
                           'description': '红色女士单鞋主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                           'download_queries': ['shoes'],
                           'name': '红色女士单鞋',
                           'original_price': 142.0,
                           'price': 116.0,
                           'seller_name': 'xiaoming'},
 'wear-tote-soft': {'category': '潮流穿搭',
                    'description': '派对造型眼镜主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                    'download_queries': ['party glasses'],
                    'name': '派对造型眼镜',
                    'original_price': 126.0,
                    'price': 99.0,
                    'seller_name': 'xiaoming'},
 'wear-tshirt-graphic': {'category': '潮流穿搭',
                         'description': '绿黑拼色眼镜主体清楚、背景干净，适合在潮流穿搭页面中直接展示，商品名称与主图保持一致。',
                         'download_queries': ['glasses'],
                         'name': '绿黑拼色眼镜',
                         'original_price': 159.0,
                         'price': 129.0,
                         'seller_name': 'xiaoming'}}
